//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiservis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignar_rol_usuario
    {
        public int id { get; set; }
        public int rol { get; set; }
        public int usuario { get; set; }
        public System.DateTime fecha_asigna { get; set; }
        public bool estado { get; set; }
    
        public virtual rol rol1 { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
