//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiservis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ficha_herramienta
    {
        public int id { get; set; }
        public Nullable<int> ficha_tecnica { get; set; }
        public Nullable<int> unidad_herramienta { get; set; }
        public Nullable<int> cantidad { get; set; }
        public bool estado { get; set; }
    
        public virtual ficha_tecnica ficha_tecnica1 { get; set; }
        public virtual unidad_herramienta unidad_herramienta1 { get; set; }
    }
}
