//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiservis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class multiservisEntities : DbContext
    {
        public multiservisEntities()
            : base("name=multiservisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<asignar_rol_usuario> asignar_rol_usuario { get; set; }
        public virtual DbSet<control> control { get; set; }
        public virtual DbSet<detalle_ficha_herramienta> detalle_ficha_herramienta { get; set; }
        public virtual DbSet<detalle_ficha_material> detalle_ficha_material { get; set; }
        public virtual DbSet<detalle_reserva> detalle_reserva { get; set; }
        public virtual DbSet<detalle_servicio> detalle_servicio { get; set; }
        public virtual DbSet<ficha_tecnica> ficha_tecnica { get; set; }
        public virtual DbSet<herramienta> herramienta { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<tecnico> tecnico { get; set; }
        public virtual DbSet<tecnico_area> tecnico_area { get; set; }
        public virtual DbSet<tipo_servicio> tipo_servicio { get; set; }
        public virtual DbSet<unidad_herramienta> unidad_herramienta { get; set; }
        public virtual DbSet<unidad_material> unidad_material { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
