//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiservis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecnico_area
    {
        public int id { get; set; }
        public int tecnico { get; set; }
        public int tipo_servicio { get; set; }
        public System.DateTime fecha { get; set; }
        public string especialidad { get; set; }
        public string nivel { get; set; }
        public bool estado { get; set; }
    
        public virtual tecnico tecnico1 { get; set; }
        public virtual tipo_servicio tipo_servicio1 { get; set; }
    }
}
