//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiservis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unidad_material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unidad_material()
        {
            this.detalle_ficha_material = new HashSet<detalle_ficha_material>();
        }
    
        public int id { get; set; }
        public int material { get; set; }
        public decimal precio_compra { get; set; }
        public decimal precio_venta { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_ficha_material> detalle_ficha_material { get; set; }
        public virtual material material1 { get; set; }
    }
}
